# Generated by Django 4.2.1 on 2023-05-10 22:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Clinics', '0001_initial'),
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Users.user')),
                ('address', models.CharField(max_length=255)),
                ('sexe', models.CharField(max_length=255)),
                ('date_naissance', models.DateField()),
            ],
            bases=('Users.user',),
        ),
        migrations.CreateModel(
            name='Secretaire',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Users.user')),
                ('clinique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Clinics.clinique')),
            ],
            bases=('Users.user',),
        ),
        migrations.CreateModel(
            name='Medecin',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Users.user')),
                ('specialite', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='medecin_images/')),
                ('description', models.TextField()),
                ('address', models.CharField(max_length=255)),
                ('jours_disponible', models.CharField(max_length=255)),
                ('heure_disponible', models.CharField(max_length=255)),
                ('clinique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Clinics.clinique')),
            ],
            bases=('Users.user',),
        ),
    ]
