# Generated by Django 4.2.1 on 2023-05-18 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_patient_secretaire_medecin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medecin',
            name='image',
            field=models.ImageField(upload_to='media/medecin_images/'),
        ),
    ]
