# Generated by Django 4.2.1 on 2023-05-21 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0004_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medecin',
            name='specialite',
            field=models.CharField(choices=[('cardiology', 'Cardiology'), ('dermatology', 'Dermatology'), ('gastroenterology', 'Gastroenterology'), ('neurology', 'Neurology'), ('oncology', 'Oncology')], max_length=255),
        ),
    ]
