# Generated by Django 4.2.1 on 2023-05-21 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0005_alter_medecin_specialite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medecin',
            name='specialite',
            field=models.CharField(choices=[('cardiology', 'Cardiology'), ('dermatology', 'Dermatology'), ('gastroenterology', 'Gastroenterology'), ('neurology', 'Neurology'), ('oncology', 'Oncology'), ('ophthalmology', 'Ophthalmology'), ('pediatrics', 'Pediatrics'), ('psychiatry', 'Psychiatry'), ('urology', 'Urology'), ('others', 'Others')], max_length=255),
        ),
    ]
