# Generated by Django 4.2.1 on 2023-05-21 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0006_alter_medecin_specialite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='sexe',
            field=models.CharField(choices=[('H', 'Homme'), ('F', 'Femme')], max_length=255),
        ),
    ]
