# Generated by Django 4.2.1 on 2023-05-18 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Clinics', '0002_remove_clinique_website'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clinique',
            name='location',
        ),
    ]
