# Generated by Django 4.2.1 on 2023-05-18 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clinics', '0003_remove_clinique_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinique',
            name='image',
            field=models.ImageField(upload_to='media/clinique_images/'),
        ),
    ]
