# Generated by Django 4.2.1 on 2023-05-10 22:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Users', '0002_patient_secretaire_medecin'),
        ('Clinics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RendezVous',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('specialite', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=255)),
                ('pdf', models.FileField(upload_to='rendezvous_pdfs/')),
                ('clinique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clinique', to='Clinics.clinique')),
                ('medecin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medecin', to='Users.medecin')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient', to='Users.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Ordonnance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('observation', models.TextField()),
                ('prescription', models.TextField()),
                ('diagnostic', models.TextField()),
                ('pdf', models.FileField(upload_to='ordonnance_pdfs/')),
                ('clinique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordonnance_clinique', to='Clinics.clinique')),
                ('medecin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordonnance_medecin', to='Users.medecin')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordonnance_patient', to='Users.patient')),
            ],
        ),
        migrations.CreateModel(
            name='DossierMedical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('Maladie', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('clinique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dossier_clinique', to='Clinics.clinique')),
                ('medecin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dossier_medecin', to='Users.medecin')),
                ('ordonnance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dossier_ordonnance', to='Medicalrecords.ordonnance')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dossier_patient', to='Users.patient')),
            ],
        ),
    ]
