# Generated by Django 4.2.1 on 2023-05-18 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Medicalrecords', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordonnance',
            name='pdf',
            field=models.FileField(upload_to='media/ordonnance_pdfs/'),
        ),
        migrations.AlterField(
            model_name='rendezvous',
            name='pdf',
            field=models.FileField(upload_to='media/rendezvous_pdfs/'),
        ),
    ]
