# Generated by Django 4.2.1 on 2023-05-21 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Medicalrecords', '0002_alter_ordonnance_pdf_alter_rendezvous_pdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dossiermedical',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='ordonnance',
            name='diagnostic',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='ordonnance',
            name='observation',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='ordonnance',
            name='pdf',
            field=models.FileField(blank=True, upload_to='media/ordonnance_pdfs/'),
        ),
        migrations.AlterField(
            model_name='ordonnance',
            name='prescription',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='rendezvous',
            name='code',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='rendezvous',
            name='pdf',
            field=models.FileField(blank=True, upload_to='media/rendezvous_pdfs/'),
        ),
        migrations.AlterField(
            model_name='rendezvous',
            name='specialite',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='rendezvous',
            name='status',
            field=models.CharField(default='pending', max_length=255),
        ),
    ]
